# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PungDeong' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#Google
pod 'GoogleSignIn'

#Firebase
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'

#Alamofire
pod 'Alamofire'

#Kakao
pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKLink'  # 메시지(카카오링크)
pod 'KakaoSDKTemplate'  # 메시지 템플릿 	

  # Pods for PungDeong

  target 'PungDeongTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PungDeongUITests' do
    # Pods for testing
  end

end
